apiVersion: v1
kind: Service
metadata:
  labels:
    name: read-ext
    version: v1
    visualize: "true"
  name: read-ext
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: main-port1
---
kind: Endpoints
apiVersion: v1
metadata:
  name: read-ext
subsets:
  - addresses:
      - ip: 172.217.23.67
    ports:
      - port: 80
