apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: read
    visualize: "true"
  name: read
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: read
        app: read
    spec:
      containers:
      - image: read:v2
        name: read
        volumeMounts:
        - mountPath: /usr/src/app/config
          name: config
      volumes:
      - name: config
        configMap:
          name: read-config-map
          items:
          - key: application.properties
            path: application.properties

